/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.sistemamed.vistasRecepcionista;

import com.mycompany.sistemamed.inter.PacientesInter;
import com.mycompany.sistemamed.modelos.Pacientes;
import com.mycompany.sistemamed.vistasAdmin.PacientesImpl;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;



/**
 *
 * @author crist
 */
public class agregarPaciente extends javax.swing.JPanel {
        boolean isEdition=false;
        Pacientes edicionUsuario;
    /**
     * Creates new form num1
     */
    public agregarPaciente() {
        initComponents();
        styles();
    }
    public agregarPaciente(Pacientes paciente){
        initComponents();
        edicionUsuario= paciente;
        isEdition=true;
        styles();
    }
    private void styles(){
       title.putClientProperty( "FlatLaf.style", "font: bold $h1.regular.font" );
        title.setForeground(Color.black);
       // Configura el layout del panel verde (contenido)
             fieldNombre.putClientProperty("JTextField.placeholderText","Ingrese el nombre del paciente");
              fieldApellidos.putClientProperty("JTextField.placeholderText","Ingrese sus apellidos del paciente ");
               fieldEdad.putClientProperty("JTextField.placeholderText","Ingrese la edad del paciente");
                fieldGenero.putClientProperty("JTextField.placeholderText","Ingrese el genero, 'masculino' o 'femenino' ");
                 fieldDireccion.putClientProperty("JTextField.placeholderText","Ingrese la dirección del usuario");
                 fieldTelefono.putClientProperty("JTextField.placeholderText","Ingrese el numero de telefono del usuario");
                   fieldCorreo.putClientProperty("JTextField.placeholderText","Ingrese el correo del usuario");
                 
         if(isEdition){
             title.setText("Modificar usuario");
             btnGuardar.setText("Guardar cambios");
             if(edicionUsuario !=null){
               fieldNombre.setText(edicionUsuario.getNombre());
               fieldApellidos.setText(edicionUsuario.getApellidos());
               fieldEdad.setText(edicionUsuario.getEdad()+"");
               fieldGenero.setText(edicionUsuario.getGenero());
               fieldDireccion.setText(edicionUsuario.getDireccion());
               fieldTelefono.setText(edicionUsuario.getTelefono());
               fieldCorreo.setText(edicionUsuario.getCorreo());
             }
         }     


    }
    private void limpiar(){
      fieldNombre.setText("");
      fieldApellidos.setText("");
      fieldEdad.setText("");
      fieldGenero.setText("");
      fieldDireccion.setText("");
      fieldTelefono.setText("");
      fieldCorreo.setText("");
      
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenido = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        fieldApellidos = new javax.swing.JTextField();
        fieldNombre = new javax.swing.JTextField();
        fieldEdad = new javax.swing.JTextField();
        fieldGenero = new javax.swing.JTextField();
        fieldDireccion = new javax.swing.JTextField();
        fieldTelefono = new javax.swing.JTextField();
        fieldCorreo = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();

        contenido.setBackground(new java.awt.Color(204, 255, 204));

        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Agregar nuevo paciente");
        title.setToolTipText("");

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellidos");

        jLabel3.setText("Edad");

        jLabel4.setText("Genero");

        jLabel5.setText("Direccion");

        jLabel6.setText("Telefono");

        jLabel7.setText("Correo");

        fieldApellidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldApellidosActionPerformed(evt);
            }
        });

        fieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNombreActionPerformed(evt);
            }
        });

        fieldEdad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldEdadActionPerformed(evt);
            }
        });

        fieldGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldGeneroActionPerformed(evt);
            }
        });

        fieldDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldDireccionActionPerformed(evt);
            }
        });

        fieldTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldTelefonoActionPerformed(evt);
            }
        });

        fieldCorreo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldCorreoActionPerformed(evt);
            }
        });

        btnGuardar.setText("Agregar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(9, 9, 9))
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fieldApellidos)
                            .addComponent(fieldNombre)
                            .addComponent(fieldEdad, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldGenero)
                            .addComponent(fieldDireccion, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldTelefono, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(fieldCorreo, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(btnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(28, 28, 28))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(fieldApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(fieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(fieldGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(fieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(fieldTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(fieldCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(jButton1))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(contenidoLayout.createSequentialGroup()
                .addGap(140, 140, 140)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(86, 86, 86))
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fieldApellidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldApellidosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldApellidosActionPerformed

    private void fieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNombreActionPerformed

    private void fieldEdadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldEdadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldEdadActionPerformed

    private void fieldGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldGeneroActionPerformed

    private void fieldDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldDireccionActionPerformed

    private void fieldTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldTelefonoActionPerformed

    private void fieldCorreoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldCorreoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldCorreoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
       
        String nombre=fieldNombre.getText();
        String apellidos=fieldApellidos.getText();
        String edad=fieldEdad.getText();
        String genero=fieldGenero.getText();
        String direccion=fieldDireccion.getText();
        String telefono=fieldTelefono.getText();
        String correo=fieldCorreo.getText();
        
    //Validadciones para los campos
        if(nombre.isEmpty()||apellidos.isEmpty()||edad.isEmpty()||genero.isEmpty()||direccion.isEmpty()||telefono.isEmpty()||correo.isEmpty()){
              
             javax.swing.JOptionPane.showMessageDialog(this,"Debe rellenar todos los campos","Aviso",javax.swing.JOptionPane.ERROR_MESSAGE );
             fieldNombre.requestFocus();
            return;
        }
        try{
            if(!edad.matches("-?\\d+")){
             throw new NumberFormatException();
            }
            int aux=Integer.parseInt(edad);
         if(aux<0){
             javax.swing.JOptionPane.showMessageDialog(this,
                "¡Por favor Introduce una edad valida!.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                fieldEdad.requestFocus();
            return;
         }   
        }catch(NumberFormatException e){
            javax.swing.JOptionPane.showMessageDialog(this,
            "La edad debe ser un número válido", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            fieldEdad.requestFocus();
             return;
        }
        
        
       try {
        // Verifica que el número contenga solo dígitos
        if (!telefono.matches("\\d+")) {
        throw new NumberFormatException();
        }

        // Verifica la longitud del número
        if (telefono.length() < 10) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "El número de teléfono debe tener más de 10 dígitos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                fieldTelefono.requestFocus();
            return;
        }
            } catch (NumberFormatException e) {
             javax.swing.JOptionPane.showMessageDialog(this,
                "Número de teléfono inválido. Solo se permiten dígitos.", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                fieldTelefono.requestFocus();
            return;
            }

         if (!correo.matches("^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$")) {
                     javax.swing.JOptionPane.showMessageDialog(this,
            "Inserte un correo válido", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            fieldCorreo.requestFocus();
            return;
            }

         Pacientes paciente= isEdition ? edicionUsuario: new  Pacientes();
         paciente.setNombre(nombre);
         paciente.setApellidos(apellidos);
         paciente.setEdad(Integer.parseInt(edad));
         paciente.setGenero(genero);
         paciente.setDireccion(direccion);
         paciente.setTelefono(telefono);
         paciente.setCorreo(correo);
         
         try{
            PacientesInter inter=new PacientesImpl();
            if(!isEdition) 
             inter.registrar(paciente);
            else
                inter.modificar(paciente);
            String mensaje=isEdition ? "modificado":"registrado";
             javax.swing.JOptionPane.showMessageDialog(this,
            "Se ha "+mensaje+" con exito", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
             if(!isEdition)
             limpiar();
        }catch(Exception e){
           String mensajeError=isEdition ? "modificado":"registrado";
             javax.swing.JOptionPane.showMessageDialog(this,
            "Ocurrio un error al"+mensajeError+" un usuaairo", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGuardar;
    private javax.swing.JPanel contenido;
    private javax.swing.JTextField fieldApellidos;
    private javax.swing.JTextField fieldCorreo;
    private javax.swing.JTextField fieldDireccion;
    private javax.swing.JTextField fieldEdad;
    private javax.swing.JTextField fieldGenero;
    private javax.swing.JTextField fieldNombre;
    private javax.swing.JTextField fieldTelefono;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
