/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.sistemamed.vistasRecepcionista;

import com.mycompany.sistemamed.vistasAdmin.CitasImpl;
import com.mycompany.sistemamed.inter.CitasInter;
import com.mycompany.sistemamed.modelos.Citas;
import com.toedter.calendar.JDateChooser;
import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author crist
 */
public class citasMedicas extends javax.swing.JPanel {
    boolean isEdition=false;
      Citas  edicionCita;
    /**
     * Creates new form num1
     */
    public citasMedicas() {
        initComponents();
        styles();
        cargarAgenda();
    }
    public void parametros(Citas cita,boolean esOno){
      isEdition=esOno;
      edicionCita=cita;
      styles();
    }   
   
    
    private void styles(){
       title.putClientProperty( "FlatLaf.style", "font: bold $h1.regular.font" );
        title.setForeground(Color.black);
        
       jLabel1.putClientProperty( "FlatLaf.style", "font: bold $h.regular.font" );
        jLabel1.setForeground(Color.WHITE);
       jLabel2.putClientProperty( "FlatLaf.style", "font: bold $h.regular.font" );
        jLabel2.setForeground(Color.WHITE);
        jLabel3.putClientProperty( "FlatLaf.style", "font: bold $h.regular.font" );
        jLabel3.setForeground(Color.WHITE);
        jLabel4.putClientProperty( "FlatLaf.style", "font: bold $h.regular.font" );
        jLabel4.setForeground(Color.WHITE);
        
        if(isEdition){
          if(edicionCita!=null){
              String hora=edicionCita.getHora();
              if(hora.contains(":")){
              hora=hora.substring(0,5);
              }
             txtFecha.setText(edicionCita.getFecha());
             comboHora.setSelectedItem(hora);
             
             txtPaciente.setText(edicionCita.getPaciente());
             txtMotivo.setText(edicionCita.getMotivo());
             btnAgregar.setText("Guardar cambios");
             btnEliminar.setText("Cancelar");
          }
        }
        
    }
   
     private void cargarAgenda(){
        //Cargar los usuarios en la tabla
        try{
               CitasInter cita=new CitasImpl();
               DefaultTableModel model= (DefaultTableModel)Calendario.getModel();
            
               // List<Citas> lista=cita.listar();
               cita.listar().forEach((u) ->   
                 model.addRow(new Object[]{u.getIdCita(), u.getFecha(),u.getHora(),u.getPaciente(),u.getMotivo(),u.getEstado()}));
        }catch(Exception e){
                System.out.println(e.getMessage());
        }
   
      
    }
    
     

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenido = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        txtPaciente = new javax.swing.JTextField();
        txtMotivo = new javax.swing.JTextField();
        btnEliminar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        comboHora = new javax.swing.JComboBox<>();
        calendario = new javax.swing.JScrollPane();
        Calendario = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        contenido.setBackground(new java.awt.Color(255, 255, 255));
        contenido.setRequestFocusEnabled(false);

        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Citas medicas");
        title.setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(4, 48, 49));
        jPanel1.setMaximumSize(new java.awt.Dimension(200, 400));

        btnAgregar.setBackground(new java.awt.Color(12, 149, 155));
        btnAgregar.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel1.setText("Fecha");

        jLabel2.setText("Hora");

        jLabel3.setText("Paciente ID");

        jLabel4.setText("Motvio");

        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });

        txtPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPacienteActionPerformed(evt);
            }
        });

        txtMotivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMotivoActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(12, 149, 155));
        btnEliminar.setFont(new java.awt.Font("Segoe UI Emoji", 1, 14)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        comboHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "08:30", "09:30", "10:00", "11:30", "12:00", "13:00", "13:30", "14:00", "14:30", "15:00" }));

        Calendario.setFont(new java.awt.Font("Segoe UI Symbol", 1, 12)); // NOI18N
        Calendario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Folio", "Fecha", "Hora", "Paciente", "Motivo", "Estado"
            }
        ));
        Calendario.setCellSelectionEnabled(true);
        Calendario.setName(""); // NOI18N
        Calendario.setShowGrid(true);
        calendario.setViewportView(Calendario);

        btnEditar.setForeground(new java.awt.Color(0, 0, 0));
        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnBorrar.setForeground(new java.awt.Color(0, 0, 0));
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(txtFecha)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPaciente))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMotivo))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(btnAgregar)
                                .addGap(38, 38, 38)
                                .addComponent(btnEliminar)))
                        .addGap(0, 72, Short.MAX_VALUE)))
                .addGap(47, 47, 47))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBorrar)
                .addGap(8, 8, 8))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel1))
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(comboHora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(calendario, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditar)
                    .addComponent(btnBorrar))
                .addContainerGap())
        );

        javax.swing.GroupLayout contenidoLayout = new javax.swing.GroupLayout(contenido);
        contenido.setLayout(contenidoLayout);
        contenidoLayout.setHorizontalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(contenidoLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(158, 158, 158))
        );
        contenidoLayout.setVerticalGroup(
            contenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenidoLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(title)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(197, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:
        String fecha=txtFecha.getText().trim();
        String hora=(String)comboHora.getSelectedItem();
        String paciente=txtPaciente.getText().trim();
        String motivo=txtMotivo.getText().trim();
     
        
         if(fecha.isEmpty()||hora.isEmpty()||paciente.isEmpty()||motivo.isEmpty()){
             javax.swing.JOptionPane.showMessageDialog(this,"Debe rellenar todos los campos","Aviso",javax.swing.JOptionPane.ERROR_MESSAGE );
             txtFecha.requestFocus();
            return;
        }
        
        Citas cita=isEdition ? edicionCita :new Citas();
        cita.setFecha(fecha);
        cita.setHora(hora);
        cita.setPaciente(paciente);
        cita.setMotivo(motivo);
         
        try{
            CitasInter inter=new CitasImpl();
            System.out.println(isEdition);
              if(!isEdition)
                inter.registrar(cita);
              else{
                  
                  inter.modificar(cita);
                  System.out.print(cita.getHora());
              }
              String mensa=isEdition ? "Modificado":"Registrado";
             javax.swing.JOptionPane.showMessageDialog(this,
            "Se ha "+mensa+ "con exito con exito", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
              DefaultTableModel model= (DefaultTableModel)Calendario.getModel();
              model.setRowCount(0);
              cargarAgenda();
        }catch(Exception e){
                String mensajeError=isEdition ? "modificar":"registrar";
             javax.swing.JOptionPane.showMessageDialog(this,
            "Ocurrio un error al "+mensajeError+" una cita", "Éxito", javax.swing.JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void txtPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPacienteActionPerformed

    private void txtMotivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMotivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMotivoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         // Crear el JDateChooser
    JDateChooser dateChooser = new JDateChooser();
    dateChooser.setDateFormatString("yyyy-MM-dd"); // Puedes ajustar el formato de la fecha aquí

    // Crear un panel para mostrar el JDateChooser
    JPanel panel = new JPanel();
    panel.add(new JLabel("Selecciona una fecha:"));
    panel.add(dateChooser);

    // Mostrar el cuadro de diálogo con el JDateChooser
    int option = JOptionPane.showConfirmDialog(this, panel, "Seleccionar Fecha", JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);

    if (option == JOptionPane.OK_OPTION) {
        // Obtener la fecha seleccionada
        java.util.Date selectedDate = dateChooser.getDate();
        if (selectedDate != null) {
            // Formatear la fecha a un formato deseado
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String formattedDate = sdf.format(selectedDate);
            
            // Establecer la fecha seleccionada en jTextField2
            txtFecha.setText(formattedDate);
        } else {
            JOptionPane.showMessageDialog(this, "No se ha seleccionado ninguna fecha.");
        }
    }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // TODO add your handling code here:
        if(Calendario.getSelectedRow()>-1){
           try{
               int citaId=(int)Calendario.getValueAt(Calendario.getSelectedRow(),0);
               CitasInter cita=new CitasImpl();
               parametros(cita.getCitasId(citaId), true);
              // JOptionPane.showMessageDialog(null,cita.getCitasId(citaId).getIdCita());
               
           }catch(Exception e){
               System.out.print(e.getMessage());
           }
        }else{
            javax.swing.JOptionPane.showMessageDialog(this,"Seleccione una Cita","Aviso",javax.swing.JOptionPane.ERROR_MESSAGE );
        
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        // TODO add your handling code here:
        if(Calendario.getSelectedRows().length<=0){
            javax.swing.JOptionPane.showMessageDialog(this,"Seleccione una cita para continuar","Aviso",javax.swing.JOptionPane.ERROR_MESSAGE );    
        }else{
            
             int confirmacion=javax.swing.JOptionPane.showConfirmDialog(
            this, 
            "¿Está seguro de que desea eliminar la agenda seleccionada?", 
            "Confirmación", 
            javax.swing.JOptionPane.YES_NO_OPTION, 
            javax.swing.JOptionPane.QUESTION_MESSAGE
             );
              if(confirmacion==javax.swing.JOptionPane.YES_NO_OPTION){
               CitasInter cita=new CitasImpl();
            DefaultTableModel model=(DefaultTableModel)Calendario.getModel();
            for(int i:Calendario.getSelectedRows()){
                try{
                    cita.eliminar((int)Calendario.getValueAt(i,0));
                    
                    model.removeRow(i);
                }catch(Exception e){
                    System.out.println(e.getMessage());
                }
            }
              }
             
           
        }
        
    }//GEN-LAST:event_btnBorrarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Calendario;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JScrollPane calendario;
    private javax.swing.JComboBox<String> comboHora;
    private javax.swing.JPanel contenido;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtMotivo;
    private javax.swing.JTextField txtPaciente;
    // End of variables declaration//GEN-END:variables
}
